### ISSUE TITLE
Missing formatted message not detected when text node is not the only node

### ISSUE THREAD

**Issue by longsleep** [calm/eslint-plugin-react-intl#2] opened 2019-05-06 13:15 UTC
```
          <Button onClick={this.handleRejectClick(contact, kind)} className={classes.reject}>
            <ClearIcon className={classes.leftIcon}/>
            Reject
          </Button>
```

`Reject` is missing translation but is not detected.

**Comment by blainemuri** [comment] 2019-05-21 17:39
Hey @longsleep, the issue has been fixed with the following PR:
https://github.com/calm/eslint-plugin-react-intl/pull/3

Version 1.3.2 is live with the change

**Comment by blainemuri** [comment] 2019-05-21 18:02
Just realized I released a bug along with this version where `no trailing whitespace` is being thrown when it shouldn't. Hotfix coming shortly

**Comment by blainemuri** [comment] 2019-05-21 18:43
Okay fix for the issue is live at version `1.3.4`

**Closed by blainemuri** 2019-05-21 18:43 UTC
Labels: bug
